# 1. Create a class Employee and then do the following
• Create a data member to count the number of Employees
• Create a constructor to initialize name, family, salary, department
• Create a function to average salary
• Create a Fulltime Employee class and it should inherit the properties of Employee class
• Create the instances of Fulltime Employee class and Employee class and call their member functions.


In [1]:

class Employee:
    numberOfEmployees = 0

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.numberOfEmployees+=1


def averagesalary(employee):
    total = sum(e.salary for e in employee)
    average = total / len(employee)
    return average

class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department):
        Employee.__init__(self,name, family, salary, department)

print("Employee 1: ")
employee1 = Employee(input("Enter name: "),input("Family Members: "),int(input("Employee Salary: ")),input("Employee Department: "))
print("Employee 2: ")
employee2 = Employee(input("Enter name: "),input("Family Members: "),int(input("Employee Salary: ")),input("Employee Department: "))
print("Full Time Employee 1: ")
employee3 = FulltimeEmployee(input("Enter name: "),input("Family Members: "),int(input("Employee Salary: ")),input("Employee Department: "))
print("")
print("Number of employees: ",Employee.numberOfEmployees)
listofEmployees = [employee1, employee2]
avgsalary = averagesalary(listofEmployees)
print("Avg salary is :", avgsalary)

Employee 1: 
Enter name: Aditya
Family Members: 3
Employee Salary: 96000
Employee Department: software
Employee 2: 
Enter name: Tarak
Family Members: 4
Employee Salary: 150000
Employee Department: Film
Full Time Employee 1: 
Enter name: kajal
Family Members: 3
Employee Salary: 200000
Employee Department: Acting

Number of employees:  3
Avg salary is : 123000.0


# 2. Numpy
Using NumPy create random vector of size 20 having only float in the range 1-20.
Then reshape the array to 4 by 5
Then replace the max in each row by 0 (axis=1)
(you can NOT implement it via for loop)

In [2]:

import numpy as np

random_vector = np.random.uniform(1, 20, 20)
print(random_vector)
print("")
print("")
reshaped_array = random_vector.reshape(4, 5)
print("")
print("")
print(reshaped_array)
reshaped_array[np.arange(4), np.argmax(reshaped_array, axis=1)] = 0
print("")
print("")
print(reshaped_array)
     

[ 5.05850405 17.24529567 10.956419    1.74530366 10.51889527 17.64973231
  1.54373296 18.16798442 18.77460298 18.99489415  9.89344753 13.05497307
  2.32614783 13.71498478  9.833775    1.08792118 15.59739025  2.22892323
 16.27960697 14.47593375]




[[ 5.05850405 17.24529567 10.956419    1.74530366 10.51889527]
 [17.64973231  1.54373296 18.16798442 18.77460298 18.99489415]
 [ 9.89344753 13.05497307  2.32614783 13.71498478  9.833775  ]
 [ 1.08792118 15.59739025  2.22892323 16.27960697 14.47593375]]


[[ 5.05850405  0.         10.956419    1.74530366 10.51889527]
 [17.64973231  1.54373296 18.16798442 18.77460298  0.        ]
 [ 9.89344753 13.05497307  2.32614783  0.          9.833775  ]
 [ 1.08792118 15.59739025  2.22892323  0.         14.47593375]]
